---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'chimera2016'

SiteConfig:
  extensions:
   - CustomSiteConfig
DBField:
  extensions:
   - RichLinksExtension
LeftAndMain:
  extra_requirements_css:
   - 'mysite/css/custom.css'
Registration:
  extensions:
   - RegistrationExtension
RegistrationPage_Controller:
  extensions:
   - RegistrationPage_ControllerExtension

KickAssets:
  menu_icon: "mysite/images/sitetree_images/photo.png"
  menu_title: "Files"

ErrorPage:
  icon: "mysite/images/sitetree_images/error.png"
UserDefinedForm:
  icon: "mysite/images/sitetree_images/form.png"
  extensions:
   - UserDefinedFormExtension

SubmittedForm:
  extensions:
   - SubmittedFormExtension

Link:
  extensions:
   - LinkExtension
